### ISSUE TITLE
advanced_security_options_enabled

### ISSUE THREAD

**Issue by salim23** [lgallard/terraform-aws-elasticsearch#13]
When setting the option:  `advanced_security_options_enabled = "true"`

Terraform states that:
`Error: Error creating ElasticSearch domain: ValidationException: You must enable EnforceHTTPS in the domain endpoint options to use advanced security.`

but there is no option to enable EnforceHTTPS on the module

On the resource "**aws_elasticsearch_domain**" definition it is possible to add:

```
domain_endpoint_options {
    enforce_https = true
  }
```

**Comment by lgallard** [comment]
@salim23 I just added the `advanced_security_options`  in PR https://github.com/lgallard/terraform-aws-elasticsearch/pull/14. If you can test it I merge it right away.  

Best regards,

**Comment by lgallard** [comment]
@salim23  Now you can enforce HTTPS, please use [release 0.5.0](https://github.com/lgallard/terraform-aws-elasticsearch/releases/tag/0.5.0) or higher.

For example, you can use the variable `domain_endpoint_options_enforce_https` as shown in the
[advanced_security_options_master_user_arn](https://github.com/lgallard/terraform-aws-elasticsearch/blob/master/examples/advanced_security_options_master_user_arn/main.tf#L24
) example:


```
  advanced_security_options = {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options = {
      master_user_arn = "arn:aws:iam::123456789101:user/lgallard"
    }
  }
 domain_endpoint_options_enforce_https = true
```

Or you can  can also define it using a map as explained in the  [advanced_security_options_master_user_name_pasword](https://github.com/lgallard/terraform-aws-elasticsearch/blob/master/examples/advanced_security_options_master_user_name_pasword/main.tf#L25) example, as long with the optional `tls_security_policy`:

```
  advanced_security_options = {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options = {
      master_user_name     = "username"
      master_user_password = "T0p$ecret"
    }
  }

  domain_endpoint_options = {
    enforce_https = true
    tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
  }
```

**Comment by salim23** [comment]
@lgallard Thanks for the quick support on this!

Its working 👍

**Comment by lgallard** [comment]
@salim23  You are welcome. Thanks for reporting the issue!
