### ISSUE TITLE
Validation Exception when using master_user_arn

### ISSUE THREAD

**Issue by aws-dev-ops-github-service** [lgallard/terraform-aws-elasticsearch#15]
when applying I can see this from the plan       

 + advanced_security_options {
          + enabled                        = true
          + internal_user_database_enabled = true

          + master_user_options {
              + master_user_arn = "arn:aws:iam::123456:user/surj@myemail.io"
            }
        }

however I get the following error

aws_elasticsearch_domain.es_domain: Creating...

Error: Error creating ElasticSearch domain: ValidationException: You must provide a master username and password when the internal user database is enabled.

**Comment by lgallard** [comment]
@aws-dev-ops-github-service when `internal_user_database_enabled` is set to `true` you must provide the username and password. 

If you want to use the `master_user_arn` instead, then set `internal_user_database_enabled` to `false`.

Regards,
