### ISSUE TITLE
Elasticsearch with Cognito

### ISSUE THREAD

**Issue by surj-bains** [lgallard/terraform-aws-elasticsearch#19]
Hi,

When setting cognito enabled
and completing variables.
  cognito_options_enabled          = true
  cognito_options_identity_pool_id = "${local.cognito_options_identity_pool_id}"
  cognito_options_role_arn         = "${local.cognito_options_role_arn}"
  cognito_options_user_pool_id     = "${local.cognito_options_user_pool_id}"

terraform/terragrunt fails with 

Error: Error creating ElasticSearch domain: ValidationException: Enable fine-grained access control or apply a restrictive access policy to your domain

  on main.tf line 1, in resource "aws_elasticsearch_domain" "es_domain":
   1: resource "aws_elasticsearch_domain" "es_domain" {

although I have a policy specified.

 access_policies = templatefile("access_policies.tpl", {
    region      = "${local.aws_region}",
    account     = "${local.aws_account_id}",
    domain_name = "${local.elastic_domain}"
  })

**Comment by lgallard** [comment]
@surj-bains fine-grained options are documented [here](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html). 

To enable it with this module you have to set the `advanced_security_options`  block or the `advanced_security_options_*` variables. In the [example folder](https://github.com/lgallard/terraform-aws-elasticsearch/tree/master/examples) you have a snippet for using a master user ARN and another one using an internal database with credentials (username and password).

Regards!
