### ISSUE TITLE
Enable Ultrawarm storage option of ElasticsearchClusterConfig

### ISSUE THREAD

**Issue by neilsmith1000** [lgallard/terraform-aws-elasticsearch#20]
To minimise cost of aged indexes, S3/cache storage is available to move older index content.
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ultrawarm.html#ultrawarm-enable

Please consider adding these optional cluster properties to main.tf section dynamic "cluster_config"

    "WarmEnabled": true,
    "WarmCount": 6,
    "WarmType": "ultrawarm1.medium.elasticsearch"

**Comment by lgallard** [comment]
@neilsmith1000 that can be included using these arguments:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#warm_enabled
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#warm_count
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#warm_type

Therefore I can include them. As soon as I have time I'll do it or if it's urgent you can create a PR.

**Comment by neilsmith1000** [comment]
Thanks lgallard, not urgent it looks a useful enhancement. Appreciate all your hard work on this

**Comment by lgallard** [comment]
@neilsmith1000 release 0.6.0 addressed this issue. Thanks for reporting!

**Comment by neilsmith1000** [comment]
Awesome, thanks for looking at these options, this change is really useful.
