### ISSUE TITLE
How to configure multiple AWS ElasticSearchlogs?

### ISSUE THREAD

**Issue by spicoflorin** [lgallard/terraform-aws-elasticsearch#25]
Hi!
 I would like to configure all the AWS ES supported log types. How can I achieve this feature using your scripts?
Can you please provide an example?
I have tried this configuration, but it takes only one configuration not all of them
` log_publishing_options = {
     enabled = "true"
     log_type = "INDEX_SLOW_LOGS"
   }
     log_publishing_options= {
       enabled = "true"
       log_type = "ES_APPLICATION_LOGS"
     }
     log_publishing_options= {
        enabled = "true"
       log_type = "SEARCH_SLOW_LOGS"
     }`

Thank you

**Comment by lgallard** [comment]
Hi @spicoflorin As mentioned in #7, If you need all three logs enabled the module must be modified to include more than just one `log_publishing_options` block.

**Comment by spicoflorin** [comment]
Thank you for your response. Is still not clear for how to achieve this (I'm a newbie in terraform subject).
In my terragrunt.hcl I have added all three log_publishing_options for each of the log type (as I mentioned in my first post), and the behavior was the one that I've mentioned.
Can you please point me where do I have add these changes, and how they should look like?
A sample code will be very helpful.

**Comment by lgallard** [comment]
@spicoflorin currenty is not possible to define more than one log option.

Here https://github.com/lgallard/terraform-aws-elasticsearch/blob/master/main.tf#L107 is where the block is defined.

**Comment by spicoflorin** [comment]
Hello!
  Thank you very much for your answers. It is not urgent. I  think  it will be very helpful for the community to include these features in a future release.
Best regards, Florin

**Comment by EvanAtHelloSign** [comment]
Is this feature already implemented? If so, what's the proper way to publish different logs to different log group?
