### ISSUE TITLE
Bug: The cluster deleted and recreated after every apply

### ISSUE THREAD

**Issue by icalvete** [lgallard/terraform-aws-elasticsearch#27]
The cluster deleted and recreated after every apply

**Comment by lgallard** [comment]
@icalvete can you give us more insights?  Can you share the plan before applying?

**Comment by z05824ac** [comment]
I have the same problem
The following is the execution plan of Apply
＜Excerpt＞
# module.aws_es.aws_elasticsearch_domain.es_domain must be replaced
-/+ resource "aws_elasticsearch_domain" "es_domain" {
      ~ access_policies       = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "es:*"
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "*"
                    },
                ]
                Version   = "2012-10-17"
            }
        )
・・・
~ encrypt_at_rest {
            enabled    = true
          ~ kms_key_id = "arn:aws:kms:<kms arn>" -> "alias/aws/es" # forces replacement
        }

**Comment by z05824ac** [comment]
I have the same problem
The following is the execution plan of Apply
＜Excerpt＞
``` shell
# module.aws_es.aws_elasticsearch_domain.es_domain must be replaced
-/+ resource "aws_elasticsearch_domain" "es_domain" {
      ~ access_policies       = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "es:*"
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "*"
                    },
                ]
                Version   = "2012-10-17"
            }
        )
・・・
~ encrypt_at_rest {
enabled = true
~ kms_key_id = "arn:aws:kms:<kms-arn>" -> "alias/aws/es" # forces replacement
}
```

**Comment by lgallard** [comment]
@z05824ac in you case, replace "alias/aws/es" with your kms's ARN:

```
  encrypt_at_rest = {
    enabled    = "true"
    kms_key_id = ""arn:aws:kms:<kms-arn>""
  }
```

**Comment by z05824ac** [comment]
Sorry for late reply  
I was able to solve the problem that way Thank you!!

**Comment by lgallard** [comment]
@z05824ac I'm glad to hear that!
