### ISSUE TITLE
Add support for custom domain names on the es endpoint

### ISSUE THREAD

**Issue by Konig-Corey** [lgallard/terraform-aws-elasticsearch#29]
Looks like aws supports custom domain names now, would love to add that support. 

AWS Post about support
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-elasticsearch-service-now-supports-defining-a-custom-name-for-your-domain-endpoint/

**Comment by lgallard** [comment]
@Konig-Corey there're a couple of tickets currently open regarding this new feature:

* [AWS ElasticSearch Custom endpoint support ](https://github.com/hashicorp/terraform-provider-aws/issues/16059)
* [r/aws_elasticsearch_domain: Add custom endpoint support ](https://github.com/hashicorp/terraform-provider-aws/pull/16192)

As soon as it's available in the AWS provider I can include it in the module.

**Comment by dmytro-dorofeiev** [comment]
Hi, it seems this feature is already supported by aws provider. Could you please update the module?

**Comment by lgallard** [comment]
@dmytro-dorofeiev I'll take a look at the resource and make the needed changes that applies.

**Comment by lgallard** [comment]
@dmytro-dorofeiev @Konig-Corey this feature was included in the lasted release. Just include a block as follows:

```
  domain_endpoint_options = {
    enforce_https                   = true
    custom_endpoint_enabled         = true
    custom_endpoint                 = "lgallardo.com"
    custom_endpoint_certificate_arn = "arn:aws:acm:us-east-1:123456789101:certificate/abcd1234-ef11-abcd-1234-abcd1234efef"
  }
```

I updated the **advanced_security_options_***  in the [examples folder](https://github.com/lgallard/terraform-aws-elasticsearch/tree/master/examples) as well.
