### ISSUE TITLE
Wrong master_user_name var when enabling advanced_security_options_internal_user_database_enabled

### ISSUE THREAD

**Issue by rafaelmariotti** [lgallard/terraform-aws-elasticsearch#31]
Hi folks!
I'm using your module trying to create an ES with internal master user enabled, but Im receiving this error:

```
module.elasticsearch.aws_cloudwatch_log_resource_policy.es_aws_cloudwatch_log_resource_policy: Creating...
module.elasticsearch.aws_cloudwatch_log_group.es_cloudwatch_log_group: Creating...
module.elasticsearch.aws_cloudwatch_log_resource_policy.es_aws_cloudwatch_log_resource_policy: Creation complete after 1s [id=data-elasticsearch-policy]
module.elasticsearch.aws_cloudwatch_log_group.es_cloudwatch_log_group: Creation complete after 2s [id=data-elasticsearch-log_group]
module.elasticsearch.aws_elasticsearch_domain.es_domain: Creating...

Error: Error creating ElasticSearch domain: ValidationException: You must provide a master username and password together.
```

Here is a piece of my code as an example:

```
module "elasticsearch" {

  source  = "lgallard/elasticsearch/aws"
  version = "0.7.0"
  
  domain_name = "test"
  elasticsearch-version = "6.7"

  advanced_security_options_enabled = true
  advanced_security_options_internal_user_database_enabled = true
  advanced_security_options_master_user_username = "admin"
  advanced_security_options_master_user_password = "password"
}
```

When looking at the terraform plan, we can check that the user name is coming as a null (only password is being filled):
```
      + advanced_security_options {
          + enabled                        = true
          + internal_user_database_enabled = true

          + master_user_options {
              + master_user_password = (sensitive value)
            }
        }
```

If you take a look on main.tf, we can see that in line 23:
```
master_user_name     = lookup(lookup(advanced_security_options.value, "master_user_options"), "master_user_name", null)
```
its trying to find a `master_user_name` variable under `master_user_options`, which does not exists:
```
  master_user_options = lookup(var.advanced_security_options, "master_user_options", null) != null ? lookup(var.advanced_security_options, "master_user_options") : {
    master_user_arn      = var.advanced_security_options_internal_user_database_enabled == false ? var.advanced_security_options_master_user_arn : null
    master_user_username = var.advanced_security_options_internal_user_database_enabled == true ? var.advanced_security_options_master_user_username : null
    master_user_password = var.advanced_security_options_internal_user_database_enabled == true ? var.advanced_security_options_master_user_password : null
  }
```

the right name for this variable is `master_user_username` under `master_user_options`, not `master_user_name`.
Am I right or missing something?

PS.: This is the first fix I open for open source projects, so pardon me if I'm missing some information.

**Comment by rafaelmariotti** [comment]
I tried to create a branch, fix it and push it, but apparently, I dont have permissions to do so :(
it seems very simple to fix ;)

**Comment by lgallard** [comment]
@rafaelmariotti Thanks for reporting the issue. The wrong reference was in line 151. PR #32 fixes 

By the way, about your block definition:

```
module "elasticsearch" {

  source  = "lgallard/elasticsearch/aws"
  version = "0.7.0"
  
  domain_name = "test"
  elasticsearch-version = "6.7"

  advanced_security_options_enabled = true
  advanced_security_options_internal_user_database_enabled = true
  advanced_security_options_master_user_username = "admin"
  advanced_security_options_master_user_password = "password"
}

```

You can also write it using blocks as follows:

```
module "elasticsearch" {

  source  = "lgallard/elasticsearch/aws"
  version = "0.7.0"
  
  domain_name = "test"
  elasticsearch-version = "6.7"

  advanced_security_options = {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options = {
      master_user_name     = "admin"
      master_user_password = "password"
    }
}

```

That I think it's more easy to understand. You can see a complete snippet for [advanced_security_options_master_user_name_pasword](https://github.com/lgallard/terraform-aws-elasticsearch/blob/master/examples/advanced_security_options_master_user_name_pasword/) under the [examples folder](https://github.com/lgallard/terraform-aws-elasticsearch/tree/master/examples)

Lastly, regarding how to collaborate to the module (and any other open source project), you need to fork the repository, then make your changes and finally create a PR from your forked repository to the original repository (in this case to mine). You can check the procedure on GitHub Docs, in particular [Creating a pull request from a fork
 ](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
