### ISSUE TITLE
Add saml authentication support.

### ISSUE THREAD

**Issue by dkushner20** [lgallard/terraform-aws-elasticsearch#34]
Elasticsearch supports using saml authentication, would love to be able to utilize this.

Related Docs:
https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticsearch-service-adds-native-saml-authentication-kibana/
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/saml.html

**Comment by lgallard** [comment]
@dkushner20 according to the [AWS documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/saml.html):

> **Enabling SAML Authentication**
>You can only enable SAML authentication for Kibana on existing domains, not during the creation of new ones

It seems you have to configure it after creation, and probably that's the reason there's no such option in the [terraform resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain).

Keep in mind though that you must enable [fine-grained access control](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html) using the `advanced_security_options` attribute block. Check the the attribute definition [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#advanced_security_options)
