### ISSUE TITLE
zone_awareness_config block within cluster_config is not working

### ISSUE THREAD

**Issue by gzanotto** [lgallard/terraform-aws-elasticsearch#38]
Even the az count set to 3, it is not working, that block does not show up in the cluster_config block and ends up defaulting to 2 which is the tf default. Probably some issue in the for_each line for the dynamic zone_awareness_config block.

**Comment by lgallard** [comment]
@gzanotto using the [public example](https://github.com/lgallard/terraform-aws-elasticsearch/tree/master/examples/public), the plan shows the right settings for `cluster_config`:

```
      + cluster_config {
          + dedicated_master_count   = 3
          + dedicated_master_enabled = true
          + dedicated_master_type    = "r5.large.elasticsearch"
          + instance_count           = 3
          + instance_type            = "r5.large.elasticsearch"
          + warm_enabled             = false
          + zone_awareness_enabled   = true

          + zone_awareness_config {
              + availability_zone_count = 3
            }
        }
```
Take into account this:

> [**zone_awareness_enabled - (Optional)**](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#zone_awareness_enabled) Indicates whether zone awareness is enabled, set to true for multi-az deployment. To enable awareness with three Availability Zones, the `availability_zone_count` within the `zone_awareness_config` must be set to `3`.

And also:

> [**availability_zone_count**](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#availability_zone_count) - (Optional) Number of Availability Zones for the domain to use with` zone_awareness_enabled`. Defaults to `2`. Valid values: `2` or `3`

If you are using VPC, also check you VPC has at least 3 AZs.

**Comment by animeshjain** [comment]
I faced this issue too, it is happening because of a type casting issue i think. 

https://github.com/lgallard/terraform-aws-elasticsearch/blob/c404840296d8a518a647d40ba1064d57b8494f25/main.tf#L88

This line is using `contains(["2", "3"]...`

Changing it to `contains([2, 3]...` makes it work for 3 zones.

**Comment by lgallard** [comment]
@gzanotto @animeshjain release 0.10.0 removed the constraint. I hope it fixes for you!
