### ISSUE TITLE
Module fails if we create cloudwatch log group in same stack where we call the module

### ISSUE THREAD

**Issue by venky999** [lgallard/terraform-aws-elasticsearch#45]
Module fails if we create cloudwatch log group in same stack. We get the following error

│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/aws_es/iam.tf line 8, in resource "aws_cloudwatch_log_group" "es_cloudwatch_log_group":
│    8:   for_each = local.options
│     ├────────────────
│     │ local.options will be known only after apply
│ 
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.

Example 

`module "aws_es" {

  source  = "lgallard/elasticsearch/aws"

  domain_name           = "elasticsearch_public"
  elasticsearch_version = "7.1"

  cluster_config = {
    dedicated_master_enabled = true
    instance_count           = 3
    instance_type            = "r5.large.elasticsearch"
    zone_awareness_enabled   = true
    availability_zone_count  = 3
  }

  ebs_options = {
    ebs_enabled = "true"
    volume_size = "25"
  }

  encrypt_at_rest = {
    enabled    = true
    kms_key_id = "arn:aws:kms:us-east-1:123456789101:key/cccc103b-4ba3-5993-6fc7-b7e538b25fd8"
  }

  log_publishing_options = {
    index_slow_logs = {
      enabled                          = true
      cloudwatch_log_group_arn         = "${aws_cloudwatch_log_group.es.arn}:*"
      log_publishing_options_retention = 90
    }
    search_slow_logs = {
      enabled                  = true
      cloudwatch_log_group_arn = "${aws_cloudwatch_log_group.es.arn}:*"
    }
    es_application_logs = {
      enabled                   = true
      cloudwatch_log_group_arn = "${aws_cloudwatch_log_group.es.arn}:*"
    }
    audit_logs = {
      enabled                   = false
      cloudwatch_log_group_arn = "${aws_cloudwatch_log_group.es.arn}:*"
    }
  }

  advanced_options = {
    "rest.action.multi.allow_explicit_index" = true
  }

  domain_endpoint_options = {
    enforce_https                   = true
    custom_endpoint_enabled         = true
    custom_endpoint                 = "lgallardo.com"
    custom_endpoint_certificate_arn = "arn:aws:acm:us-east-1:123456789101:certificate/abcd1234-ef11-abcd-1234-abcd1234efef"
  }

  node_to_node_encryption_enabled                = true
  snapshot_options_automated_snapshot_start_hour = 23

  tags = {
    Owner = "sysops"
    env   = "dev"
  }

resource "aws_cloudwatch_log_group" "es" {
  name              = "test"
  retention_in_days = 90
}

`

Fixed here https://github.com/lgallard/terraform-aws-elasticsearch/pull/46

**Comment by venky999** [comment]
https://github.com/lgallard/terraform-aws-elasticsearch/pull/46

**Comment by lgallard** [comment]
@venky999 your PR was merged in 0.12.2 release!
