### ISSUE TITLE
Could you please add support of a cold storage tier for AWS OpenSearch Service ?

### ISSUE THREAD

**Issue by AlKapkone** [lgallard/terraform-aws-elasticsearch#50]
https://aws.amazon.com/ru/blogs/big-data/introducing-cold-storage-for-amazon-opensearch-service/

**Comment by AlKapkone** [comment]
<img width="814" alt="Знімок екрана 2022-06-08 о 14 14 50" src="https://user-images.githubusercontent.com/24461114/172603219-d39fc795-d9b3-4981-979c-96810af1b80f.png">
**Enable cold storage**

**Comment by AlKapkone** [comment]
Terraform - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#cold_storage_options

**Comment by lgallard** [comment]
@AlKapkone release 0.14.0 added the option. Thanks for reporting it!

**Comment by AlKapkone** [comment]
```
git push origin feature/cold-storage-variables
ERROR: Permission to lgallard/terraform-aws-elasticsearch.git denied to AlKapkone.
```

**Comment by lgallard** [comment]
@AlKapkone nice catch. You can create a PR against my repo and I'll approve it or I can take the lines from your comments. You can't push directly to other repos, that's why you need to create a PR.

I rather you create a PR, this way you will appear as a contributor!

**Comment by AlKapkone** [comment]
PR - https://github.com/lgallard/terraform-aws-elasticsearch/pull/53

**Comment by lgallard** [comment]
@AlKapkone release 0.14.1 has your changes. Thanks!!

**Comment by AlKapkone** [comment]
@lgallard Great! Thank you so much for this amazing module!
